language: python

python:
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch

before_install:
  - sudo apt-get install -y libopenmpi-dev wget unzip
  #- sudo apt-get install -y curl git libgl1-mesa-dev libgl1-mesa-glx libglew-dev libosmesa6-dev
  #- wget https://www.roboti.us/download/mjpro150_linux.zip
  #- unzip mjpro150_linux.zip -d /home/travis/.mujoco
  #- echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/home/travis/.mujoco/mjpro150/bin" >> /home/travis/.bashrc
  #- source /home/travis/.bashrc

# command to install dependencies
install:
  - pip install .
  - pip install mpi4py click

# command to run tests
script:
  - python -m tests.test_baselines
  - python -m tests.test_optimizers
  - python -m tests.test_policies
  - python -m tests.test_samplers
  - python -m tests.test_integration

notifications:
  email:
    recipients:
      - jonas.rothfuss@gmail.com
    on_success: never
    on_failure: always